apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: addressbook
spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - addressbook.192.168.56.100.nip.io
    secretName: wildcard-tls

  rules:
  - host: addressbook.192.168.56.100.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: addressbook
            port:
              number: 80